### ISSUE TITLE
Error in creating DXF

### ISSUE THREAD

**Issue by PacoH** [ocxtal/miura#1]
I installed `miura` and `dxfwrite`. 

    miura 6 12 --xcnt=3 --ycnt=6 > out.dxf

yields an invalid DXF file that contains:

	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/site-packages/miura/__init__.py", line 60, in main
		miura_script()
	  File "/usr/local/lib/python2.7/site-packages/miura/script.py", line 46, in __call__
		raise MiuraException("Unable to find script {0}".format(target_module))
	MiuraException: Unable to find script scripts.6

**Comment by ocxtal** [comment]
I tested the argument above and found the current master had a bug. I fixed it and pushed a patch. Please try it.

(And I wondered how you installed the script; the stack trace seems the script is wrapped by another (not my own) program.)

Thanks,

Hajime Suzuki

**Comment by PacoH** [comment]
Hi Hajime,

Thanks for the response. I uninstalled and re-installed `miura`–`pip install miura`.

	pip show miura
	Name: miura
	Version: 0.1.5
	Summary: a Jenkins job management tool
	Home-page: http://toumorokoshi.github.io/miura
	Author: Yusuke Tsutsumi
	Author-email: yusuke@yusuketsutsumi.com
	License: UNKNOWN
	Location: /usr/local/lib/python2.7/site-packages
	Requires: jenkinsapi, jinja2, docopt, pyyaml

Requirements were installed already.

`miura 6 12 --xcnt=3 --ycnt=6 > out.dxf`

Still got:

	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/site-packages/miura/__init__.py", line 60, in main
		miura_script()
	  File "/usr/local/lib/python2.7/site-packages/miura/script.py", line 46, in __call__
		raise MiuraException("Unable to find script {0}".format(target_module))
	MiuraException: Unable to find script scripts.6

BTW the docs do not show the syntax for actually generating a pattern. Is this correct?

As for the stack trace, that's `python 2.7` installed by `homebrew`. I'm using `OS X 10.8.5`

**Comment by ocxtal** [comment]
The miura package installed by pip (and registered at PyPI) is another miura, *a Jenkins job management tool*. (https://pypi.python.org/pypi/miura/0.1.5)

So please try the correct one, for example hitting the following commands:
```
$ git clone https://github.com/ocxtal/miura.git
$ cd miura
$ python miura.py 6 12 --xcnt=3 --ycnt=6 > out.dxf
```

Thanks,

**Comment by PacoH** [comment]
DOH! You're kidding. OK I uninstalled the wrong tool and installed yours and now it works. It generates a pretty ugly thick white lined pattern on black background. Is there any way to set the linewidth and colors? How about angle `alpha`?

**Comment by ocxtal** [comment]
The angle of parallelogram can be changed by passing `--tan` (tangent) option like `--tan=0.9` so please try it.

The line width and colors are the defaults of the dxfwrite library, and on my environments Inkscape, Autocad, and jwcad drew outputs finely. The code is very simple so please read and modify it by yourself if you want to change the style of outputs.

Thanks,

**Comment by PacoH** [comment]
OK, that worked. Are there other 'hidden' options?

**Comment by ocxtal** [comment]
The following code copied from `miura.py` clearly shows there are four options `--xcnt`, `--ycnt` and `--tan` mentioned above and `--out` to specify output filename.

```Python
	from optparse import OptionParser
	p = OptionParser(usage = "python miura.py <width> <height> > out.dxf # all dimensions are in millimeters")
	p.add_option("-t", "--tan", dest = "t", help = "tangent", type = "float", default = 0.1)
	p.add_option("-x", "--xcnt", dest = "xcnt", help = "x (width) splitting count", type = "int", default = 5)
	p.add_option("-y", "--ycnt", dest = "ycnt", help = "y (height) splitting count", type = "int", default = 3)
	p.add_option("-o", "--output", dest = "o", help = "output file name")

	(opt, args) = p.parse_args()
```

Good luck👍
